#!/usr/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later

##    gmes - GIST Maxwell's Equations Solver
##    Copyright (C) 2007-2012  Kyungwon Chun
##
##    This program is free software; you can redistribute it and/or
##    modify it under the terms of the GNU General Public
##    License as published by the Free Software Foundation; either
##    version 3 of the License, or (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##    General Public License for more details.
##
##    You should have received a copy of the GNU General Public
##    License along with this program. If not, see
##    <https://www.gnu.org/licenses/>.
##
##    Kyungwon Chun
##    kwchun@gist.ac.kr

"""Public API for GMES's Torch-only FDTD runtime."""

from math import inf

from . import (
    constant,
    geometry,
    material,
    source,
    torch_distributed,
    torch_fdtd,
    torch_output,
    torch_plan,
    torch_source,
)
from .constant import (
    ATTO,
    FEMTO,
    GIGA,
    KILO,
    MEGA,
    MICRO,
    MILLI,
    NANO,
    PETA,
    PICO,
    TERA,
    Z0,
    Ex,
    Ey,
    Ez,
    Hx,
    Hy,
    Hz,
    Jx,
    Jy,
    Jz,
    MinusX,
    MinusY,
    MinusZ,
    Mx,
    My,
    Mz,
    PlusX,
    PlusY,
    PlusZ,
    X,
    Y,
    Z,
    c0,
    eps0,
    mu0,
    pi,
)
from .geometry import (
    Block,
    Cartesian,
    Cone,
    Cylinder,
    DefaultMedium,
    Ellipsoid,
    Shell,
    Sphere,
)
from .material import (
    Const,
    Cpml,
    CriticalPoint,
    DcpAde,
    DcpPlrc,
    DcpRc,
    Dielectric,
    Dm2,
    Drude,
    DrudePole,
    Dummy,
    Lorentz,
    LorentzPole,
    Upml,
)
from .source import (
    Bandpass,
    Continuous,
    DifferentiatedGaussian,
    GaussianBeam,
    PointSource,
    TotalFieldScatteredField,
)
from .torch_distributed import (
    TorchDistributedError,
    TorchDistributedSimulation,
    TorchHaloExchange,
    TwoGpuDecomposition,
    choose_two_gpu_decomposition,
    distributed_launch_from_environment,
    rank_local_space,
)
from .torch_fdtd import (
    ComponentPlan,
    DistributedLaunch,
    ExecutionSignature,
    FlattenedStencilTerm,
    MaterialBucketPlan,
    TorchConfigurationError,
    TorchExecutionPlanner,
    TorchProbeSamples,
    TorchProbeSpec,
    TorchProbeSpectrum,
    TorchRuntimeConfig,
    TorchSimulation,
    TorchSimulationPlan,
    TorchSimulationState,
    probe_spectrum,
    read_torch_checkpoint,
    torch_runtime_diagnostics,
    write_probe_text,
    write_torch_checkpoint,
)
from .torch_source import TorchPointSourceRecord, TorchSourceLoweringContext

__all__ = [
    "geometry",
    "constant",
    "source",
    "material",
    "Cartesian",
    "DefaultMedium",
    "Cone",
    "Cylinder",
    "Block",
    "Ellipsoid",
    "Sphere",
    "Shell",
    "Ex",
    "Ey",
    "Ez",
    "Hx",
    "Hy",
    "Hz",
    "Jx",
    "Jy",
    "Jz",
    "Mx",
    "My",
    "Mz",
    "X",
    "Y",
    "Z",
    "PlusX",
    "MinusX",
    "PlusY",
    "MinusY",
    "PlusZ",
    "MinusZ",
    "Continuous",
    "Bandpass",
    "DifferentiatedGaussian",
    "PointSource",
    "TotalFieldScatteredField",
    "GaussianBeam",
    "Dummy",
    "Const",
    "Dielectric",
    "Upml",
    "Cpml",
    "DrudePole",
    "LorentzPole",
    "CriticalPoint",
    "DcpAde",
    "DcpPlrc",
    "DcpRc",
    "Drude",
    "Lorentz",
    "Dm2",
    "ComponentPlan",
    "DistributedLaunch",
    "ExecutionSignature",
    "FlattenedStencilTerm",
    "MaterialBucketPlan",
    "TorchConfigurationError",
    "TorchDistributedError",
    "TorchDistributedSimulation",
    "TorchHaloExchange",
    "TorchExecutionPlanner",
    "TorchPointSourceRecord",
    "TorchProbeSamples",
    "TorchProbeSpec",
    "TorchProbeSpectrum",
    "TorchRuntimeConfig",
    "TorchSimulation",
    "TorchSimulationPlan",
    "TorchSimulationState",
    "TorchSourceLoweringContext",
    "TwoGpuDecomposition",
    "pi",
    "c0",
    "mu0",
    "eps0",
    "Z0",
    "PETA",
    "TERA",
    "GIGA",
    "MEGA",
    "KILO",
    "MILLI",
    "MICRO",
    "NANO",
    "PICO",
    "FEMTO",
    "ATTO",
    "inf",
    "choose_two_gpu_decomposition",
    "distributed_launch_from_environment",
    "probe_spectrum",
    "rank_local_space",
    "read_torch_checkpoint",
    "torch_runtime_diagnostics",
    "write_probe_text",
    "write_torch_checkpoint",
]
