from typing import Any, Self, overload

from _typeshed import Incomplete

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

class SwigPyIterator:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def value(self): ...
    def incr(self, n: int = 1): ...
    def decr(self, n: int = 1): ...
    def distance(self, x): ...
    def equal(self, x): ...
    def copy(self): ...
    def __next__(self): ...
    def previous(self): ...
    def advance(self, n): ...
    def __eq__(self, x): ...
    def __ne__(self, x): ...
    def __iadd__(self, n): ...
    def __isub__(self, n: int) -> Self: ...  # type: ignore[misc]  # SWIG accepts only offsets in-place but also supports iterator distance.
    def __add__(self, n): ...
    @overload
    def __sub__(self, other: int) -> Self: ...
    @overload
    def __sub__(self, other: Self) -> int: ...
    def __iter__(self): ...

class OracleIndexVector:
    thisown: Incomplete
    def iterator(self): ...
    def __iter__(self): ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __delitem__(self, *args) -> None: ...
    def __getitem__(self, *args): ...
    def __setitem__(self, *args) -> None: ...
    def pop(self): ...
    def append(self, x): ...
    def empty(self): ...
    def size(self): ...
    def swap(self, v): ...
    def begin(self): ...
    def end(self): ...
    def rbegin(self): ...
    def rend(self): ...
    def clear(self): ...
    def get_allocator(self): ...
    def pop_back(self): ...
    def erase(self, *args): ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x): ...
    def front(self): ...
    def back(self): ...
    def assign(self, n, x): ...
    def resize(self, *args): ...
    def insert(self, *args): ...
    def reserve(self, n): ...
    def capacity(self): ...
    __swig_destroy__: Incomplete

class OracleStateVector:
    thisown: Incomplete
    def iterator(self): ...
    def __iter__(self): ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __delitem__(self, *args) -> None: ...
    def __getitem__(self, *args): ...
    def __setitem__(self, *args) -> None: ...
    def pop(self): ...
    def append(self, x): ...
    def empty(self): ...
    def size(self): ...
    def swap(self, v): ...
    def begin(self): ...
    def end(self): ...
    def rbegin(self): ...
    def rend(self): ...
    def clear(self): ...
    def get_allocator(self): ...
    def pop_back(self): ...
    def erase(self, *args): ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x): ...
    def front(self): ...
    def back(self): ...
    def assign(self, n, x): ...
    def resize(self, *args): ...
    def insert(self, *args): ...
    def reserve(self, n): ...
    def capacity(self): ...
    __swig_destroy__: Incomplete

def openmp_enabled(): ...
def openmp_max_threads(): ...
def openmp_cell_threshold(): ...

class PwMaterialParam:
    thisown: Incomplete
    __swig_destroy__: Incomplete
    def __init__(self) -> None: ...

class UpdateOffsets:
    thisown: Incomplete
    target: Incomplete
    in1_first: Incomplete
    in1_second: Incomplete
    in2_first: Incomplete
    in2_second: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpdateRun:
    thisown: Incomplete
    offsets: Incomplete
    strides: Incomplete
    begin: Incomplete
    size: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

def make_index(data, size): ...

class PwMaterialParamVector:
    thisown: Incomplete
    def iterator(self): ...
    def __iter__(self): ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __delitem__(self, *args) -> None: ...
    def __getitem__(self, *args): ...
    def __setitem__(self, *args) -> None: ...
    def pop(self): ...
    def append(self, x): ...
    def empty(self): ...
    def size(self): ...
    def swap(self, v): ...
    def begin(self): ...
    def end(self): ...
    def rbegin(self): ...
    def rend(self): ...
    def clear(self): ...
    def get_allocator(self): ...
    def pop_back(self): ...
    def erase(self, *args): ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x): ...
    def front(self): ...
    def back(self): ...
    def assign(self, n, x): ...
    def resize(self, *args): ...
    def insert(self, *args): ...
    def reserve(self, n): ...
    def capacity(self): ...
    __swig_destroy__: Incomplete

class ElectricParamReal(PwMaterialParam):
    thisown: Incomplete
    eps_inf: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

cvar: Incomplete
dm2_max_iterations: Incomplete

class MagneticParamReal(PwMaterialParam):
    thisown: Incomplete
    mu_inf: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class PwMaterialReal:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def name(self) -> str: ...
    def attach(self, idx: tuple[int, int, int], parameter: PwMaterialParam) -> None: ...
    def attach_many(self, indices: Any, parameters: Any) -> None: ...
    def finalize(
        self,
        component: int,
        target_dim1: int,
        target_dim2: int,
        target_dim3: int,
        in1_dim1: int,
        in1_dim2: int,
        in1_dim3: int,
        in2_dim1: int,
        in2_dim2: int,
        in2_dim3: int,
    ): ...
    def is_finalized(self) -> bool: ...
    def plan_size(self) -> int: ...
    def plan_run_count(self) -> int: ...
    def plan_is_parallel_safe(self) -> bool: ...
    def plan_bytes(self) -> int: ...
    def oracle_index_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def oracle_indices(self): ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def reserve(self, capacity: int) -> None: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def find(self, idx): ...
    def merge(self, pm: Self) -> None: ...
    def idx_size(self) -> int: ...

class MaterialElectricReal(PwMaterialReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def find(self, idx): ...
    __swig_destroy__: Incomplete

class MaterialMagneticReal(PwMaterialReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def find(self, idx): ...
    __swig_destroy__: Incomplete

class DummyElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyMagneticReal(MaterialMagneticReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyExReal(DummyElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyEyReal(DummyElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyEzReal(DummyElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHxReal(DummyMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHyReal(DummyMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHzReal(DummyMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    value: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    value: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstMagneticReal(MaterialMagneticReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstExReal(ConstElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstEyReal(ConstElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstEzReal(ConstElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHxReal(ConstMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHyReal(ConstMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHzReal(ConstMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class DielectricMagneticReal(MaterialMagneticReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class DielectricExReal(DielectricElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricEyReal(DielectricElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricEzReal(DielectricElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHxReal(DielectricMagneticReal):
    thisown: Incomplete
    def update_all(self, hx, ez, ey, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHyReal(DielectricMagneticReal):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHzReal(DielectricMagneticReal):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    c1: Incomplete
    c2: Incomplete
    c3: Incomplete
    c4: Incomplete
    c5: Incomplete
    c6: Incomplete
    d: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    c1: Incomplete
    c2: Incomplete
    c3: Incomplete
    c4: Incomplete
    c5: Incomplete
    c6: Incomplete
    b: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class UpmlMagneticReal(MaterialMagneticReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class UpmlExReal(UpmlElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlEyReal(UpmlElectricReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlEzReal(UpmlElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHxReal(UpmlMagneticReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHyReal(UpmlMagneticReal):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHzReal(UpmlMagneticReal):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    b1: Incomplete
    b2: Incomplete
    c1: Incomplete
    c2: Incomplete
    kappa1: Incomplete
    kappa2: Incomplete
    psi1: Incomplete
    psi2: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    b1: Incomplete
    b2: Incomplete
    c1: Incomplete
    c2: Incomplete
    kappa1: Incomplete
    kappa2: Incomplete
    psi1: Incomplete
    psi2: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class CpmlMagneticReal(MaterialMagneticReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class CpmlExReal(CpmlElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlEyReal(CpmlElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlEzReal(CpmlElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHxReal(CpmlMagneticReal):
    thisown: Incomplete
    def update_all(self, hx, ez, ey, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHyReal(CpmlMagneticReal):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHzReal(CpmlMagneticReal):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    a: Incomplete
    c: Incomplete
    q_now: Incomplete
    q_new: Incomplete
    def set(self, a, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def dps_sum(self, init, drude_param): ...
    def update_q(self, e_now, drude_param): ...
    __swig_destroy__: Incomplete

class DrudeExReal(DrudeElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeEyReal(DrudeElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeEzReal(DrudeElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHxReal(DielectricHxReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHyReal(DielectricHyReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHzReal(DielectricHzReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    a: Incomplete
    c: Incomplete
    l_now: Incomplete
    l_new: Incomplete
    def set(self, a, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def lps_sum(self, init, lorentz_param): ...
    def update_l(self, e_now, lorentz_param): ...
    __swig_destroy__: Incomplete

class LorentzExReal(LorentzElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzEyReal(LorentzElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzEzReal(LorentzElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHxReal(DielectricHxReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHyReal(DielectricHyReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHzReal(DielectricHzReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    a: Incomplete
    b: Incomplete
    c: Incomplete
    e_old: Incomplete
    q_old: Incomplete
    q_now: Incomplete
    p_old: Incomplete
    p_now: Incomplete
    def set(self, a, b, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def dps_sum(self, init, dcp_param): ...
    def cps_sum(self, init, dcp_param): ...
    def update_q(self, e_old, e_now, e_new, dcp_param): ...
    def update_p(self, e_old, e_now, e_new, dcp_param): ...
    __swig_destroy__: Incomplete

class DcpAdeExReal(DcpAdeElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeEyReal(DcpAdeElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeEzReal(DcpAdeElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHxReal(DielectricHxReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHyReal(DielectricHyReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHzReal(DielectricHzReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    a: Incomplete
    b: Incomplete
    c: Incomplete
    psi_dp_re: Incomplete
    psi_dp_im: Incomplete
    psi_cp_re: Incomplete
    psi_cp_im: Incomplete
    def set(self, a, b, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcMagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_psi_dp(self, e_now, e_new, dcp_param): ...
    def update_psi_cp(self, e_now, e_new, dcp_param): ...
    def psi_total(self, dcp_param): ...
    __swig_destroy__: Incomplete

class DcpPlrcExReal(DcpPlrcElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcEyReal(DcpPlrcElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcEzReal(DcpPlrcElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHxReal(DielectricHxReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHyReal(DielectricHyReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHzReal(DielectricHzReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ElectricParamCmplx(PwMaterialParam):
    thisown: Incomplete
    eps_inf: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class MagneticParamCmplx(PwMaterialParam):
    thisown: Incomplete
    mu_inf: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class PwMaterialCmplx:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def name(self) -> str: ...
    def attach(self, idx: tuple[int, int, int], parameter: PwMaterialParam) -> None: ...
    def attach_many(self, indices: Any, parameters: Any) -> None: ...
    def finalize(
        self,
        component: int,
        target_dim1: int,
        target_dim2: int,
        target_dim3: int,
        in1_dim1: int,
        in1_dim2: int,
        in1_dim3: int,
        in2_dim1: int,
        in2_dim2: int,
        in2_dim3: int,
    ): ...
    def is_finalized(self) -> bool: ...
    def plan_size(self) -> int: ...
    def plan_run_count(self) -> int: ...
    def plan_is_parallel_safe(self) -> bool: ...
    def plan_bytes(self) -> int: ...
    def oracle_index_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def oracle_indices(self): ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def reserve(self, capacity: int) -> None: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def find(self, idx): ...
    def merge(self, pm: Self) -> None: ...
    def idx_size(self) -> int: ...

class MaterialElectricCmplx(PwMaterialCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def find(self, idx): ...
    __swig_destroy__: Incomplete

class MaterialMagneticCmplx(PwMaterialCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def find(self, idx): ...
    __swig_destroy__: Incomplete

class DummyElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyMagneticCmplx(MaterialMagneticCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyExCmplx(DummyElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyEyCmplx(DummyElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyEzCmplx(DummyElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHxCmplx(DummyMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHyCmplx(DummyMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DummyHzCmplx(DummyMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    value: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    value: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstMagneticCmplx(MaterialMagneticCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_all(
        self, inplace_field, in_field1, in_field2, d1, d2, dt, n
    ) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstExCmplx(ConstElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstEyCmplx(ConstElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstEzCmplx(ConstElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHxCmplx(ConstMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHyCmplx(ConstMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class ConstHzCmplx(ConstMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class DielectricMagneticCmplx(MaterialMagneticCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class DielectricExCmplx(DielectricElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricEyCmplx(DielectricElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricEzCmplx(DielectricElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHxCmplx(DielectricMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hx, ez, ey, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHyCmplx(DielectricMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DielectricHzCmplx(DielectricMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    c1: Incomplete
    c2: Incomplete
    c3: Incomplete
    c4: Incomplete
    c5: Incomplete
    c6: Incomplete
    d: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    c1: Incomplete
    c2: Incomplete
    c3: Incomplete
    c4: Incomplete
    c5: Incomplete
    c6: Incomplete
    b: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class UpmlMagneticCmplx(MaterialMagneticCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class UpmlExCmplx(UpmlElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlEyCmplx(UpmlElectricCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlEzCmplx(UpmlElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHxCmplx(UpmlMagneticCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHyCmplx(UpmlMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class UpmlHzCmplx(UpmlMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    b1: Incomplete
    b2: Incomplete
    c1: Incomplete
    c2: Incomplete
    kappa1: Incomplete
    kappa2: Incomplete
    psi1: Incomplete
    psi2: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    b1: Incomplete
    b2: Incomplete
    c1: Incomplete
    c2: Incomplete
    kappa1: Incomplete
    kappa2: Incomplete
    psi1: Incomplete
    psi2: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class CpmlMagneticCmplx(MaterialMagneticCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_mu_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class CpmlExCmplx(CpmlElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlEyCmplx(CpmlElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlEzCmplx(CpmlElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHxCmplx(CpmlMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hx, ez, ey, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHyCmplx(CpmlMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class CpmlHzCmplx(CpmlMagneticCmplx):
    thisown: Incomplete
    def update_all(self, hz, ey, ex, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    a: Incomplete
    c: Incomplete
    q_now: Incomplete
    q_new: Incomplete
    def set(self, a, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def dps_sum(self, init, drude_param): ...
    def update_q(self, e_now, drude_param): ...
    __swig_destroy__: Incomplete

class DrudeExCmplx(DrudeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeEyCmplx(DrudeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeEzCmplx(DrudeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHxCmplx(DielectricHxCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHyCmplx(DielectricHyCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DrudeHzCmplx(DielectricHzCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    a: Incomplete
    c: Incomplete
    l_now: Incomplete
    l_new: Incomplete
    def set(self, a, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def lps_sum(self, init, lorentz_param): ...
    def update_l(self, e_now, lorentz_param): ...
    __swig_destroy__: Incomplete

class LorentzExCmplx(LorentzElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzEyCmplx(LorentzElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzEzCmplx(LorentzElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHxCmplx(DielectricHxCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHyCmplx(DielectricHyCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class LorentzHzCmplx(DielectricHzCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    a: Incomplete
    b: Incomplete
    c: Incomplete
    e_old: Incomplete
    q_old: Incomplete
    q_now: Incomplete
    p_old: Incomplete
    p_now: Incomplete
    def set(self, a, b, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def dps_sum(self, init, dcp_param): ...
    def cps_sum(self, init, dcp_param): ...
    def update_q(self, e_old, e_now, e_new, dcp_param): ...
    def update_p(self, e_old, e_now, e_new, dcp_param): ...
    __swig_destroy__: Incomplete

class DcpAdeExCmplx(DcpAdeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeEyCmplx(DcpAdeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeEzCmplx(DcpAdeElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHxCmplx(DielectricHxCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHyCmplx(DielectricHyCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpAdeHzCmplx(DielectricHzCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcElectricParamCmplx(ElectricParamCmplx):
    thisown: Incomplete
    a: Incomplete
    b: Incomplete
    c: Incomplete
    psi_dp_re: Incomplete
    psi_dp_im: Incomplete
    psi_cp_re: Incomplete
    psi_cp_im: Incomplete
    def set(self, a, b, c): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcMagneticParamCmplx(MagneticParamCmplx):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcElectricCmplx(MaterialElectricCmplx):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    def update_psi_dp(self, e_now, e_new, dcp_param): ...
    def update_psi_cp(self, e_now, e_new, dcp_param): ...
    def psi_total(self, dcp_param): ...
    __swig_destroy__: Incomplete

class DcpPlrcExCmplx(DcpPlrcElectricCmplx):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcEyCmplx(DcpPlrcElectricCmplx):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcEzCmplx(DcpPlrcElectricCmplx):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHxCmplx(DielectricHxCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHyCmplx(DielectricHyCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class DcpPlrcHzCmplx(DielectricHzCmplx):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2ElectricParamReal(ElectricParamReal):
    thisown: Incomplete
    omega: Incomplete
    n_atom: Incomplete
    rho30: Incomplete
    gamma: Incomplete
    t1: Incomplete
    t2: Incomplete
    hbar: Incomplete
    rtol: Incomplete
    u: Incomplete
    a_scratch: Incomplete
    b_scratch: Incomplete
    u_new_scratch: Incomplete
    u_previous_scratch: Incomplete
    def set(self, omega, n): ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2MagneticParamReal(MagneticParamReal):
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2ElectricReal(MaterialElectricReal):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_rho(self, idx, bin, rho_idx, t): ...
    def get_u(self, idx, t, u): ...
    def get_v(self, idx, t, v): ...
    def get_w(self, idx, t, w): ...
    def name(self) -> str: ...
    def get_eps_inf(self, idx: tuple[int, int, int]) -> float: ...
    def attach(
        self, idx: tuple[int, int, int], pm_param_ptr: PwMaterialParam
    ) -> None: ...
    def merge(self, pm_ptr: Self) -> None: ...
    def oracle_state(self): ...
    def oracle_state_bytes(self) -> int: ...
    def oracle_parameter_bytes(self) -> int: ...
    __swig_destroy__: Incomplete

class Dm2ExReal(Dm2ElectricReal):
    thisown: Incomplete
    def update_all(self, ex, hz, hy, dy, dz, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2EyReal(Dm2ElectricReal):
    thisown: Incomplete
    def update_all(self, ey, hx, hz, dz, dx, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2EzReal(Dm2ElectricReal):
    thisown: Incomplete
    def update_all(self, ez, hy, hx, dx, dy, dt, n) -> None: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2HxReal(DielectricHxReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2HyReal(DielectricHyReal):
    thisown: Incomplete
    def update_all(self, hy, ex, ez, dz, dx, dt, n) -> None: ...
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Dm2HzReal(DielectricHzReal):
    thisown: Incomplete
    def name(self) -> str: ...
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
